fail_on_severity: moderate
allow_licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - CC0-1.0
deny_licenses:
  - MS-PL
  - CC-BY-NC
vulnerability_check: true
license_check: true
